### ISSUE TITLE
fitting front face issue

### ISSUE THREAD

**Issue by cizmek777** [Yinghao-Li/3DMM-fitting#3]
Is there a way to fit face without profile face?
I use these code in function ```fit_fandp_to_landmarks_linear()``` , but it doesn't fit facial expression well.
```
num_front_landmarks = len(front_landmarks)
num_profile_landmarks = len(profile_landmarks) 
#num_total_landmarks = num_front_landmarks + num_profile_landmarks 
num_total_landmarks = num_front_landmarks 
```
test data:
*save file as 'image_0146.pts'*
[image_0146.txt](https://github.com/Yinghao-Li/3DMM-fitting/files/2237772/image_0146.txt)

*save image as 'image_0146.png'*
![image_0146](https://user-images.githubusercontent.com/41460228/43354484-0533a4da-9280-11e8-9039-ebff5beb9b97.png)

and here is the result:
https://i.loli.net/2018/07/28/5b5c2406b1053.png

**Comment by Yinghao-Li** [comment]
I'm sorry that I didn't reply earlier.

In this case, you can try the function `core\fitting.fit_shape_and_pose()`. This function is designed to fit frontal face without profile.

However, as this project is based on [eos](https://github.com/patrikhuber/eos), I would suggest you use their python API directly if you do not need profile-fitting. Their project runs much faster since it is written in C++ while mine is completely in Python.

**Comment by cizmek777** [comment]
thanks, it works.
